name: Export Blog Content
on:
  push:
    branches:
      - master
jobs:
  export-blog-content:
    runs-on:  "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
          cache: npm

      - name: Install ghost
        run: npm install -g ghost-cli@1.23.1

      - name: Initial ghost
        run: make init

      - name: Run ghost
        run: make start

      - name: Export content
        run: make build
        
        
